language: en-US
reviews:
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  auto_review:
    enabled: true
    drafts: false
  path_instructions:
    - path: "**/*.py"
      instructions: >
        No print() in production. Use logging. No bare except. Files < 600 lines.
        Flag stub returns (return [], return {}, return None) without TODO marker.
        Flag empty catch/except blocks that swallow errors.
        Flag pinned dependencies (== in requirements.txt) where the version does not exist
        on PyPI. Verify version strings look realistic (not hallucinated by LLM).
    - path: "**/*.ts"
      instructions: >
        No any types (use unknown). No console.log. No commented-out code.
        Flag stub returns (return [], return {}, return null, return '') in non-test files.
        Flag empty catch blocks that swallow errors.
        Flag .where().where() chaining in Drizzle (must use and()).
        Flag import Redis from 'ioredis' (must use { Redis }).
        Flag copy-paste drift: near-identical code blocks (3+ lines) with subtle differences
        (e.g. one updated, others not). Suggest extracting a shared helper or fixing the inconsistency.
    - path: "**/*.tsx"
      instructions: >
        No any types (use unknown). No console.log. No commented-out code.
        Flag hardcoded strings where env vars or config should be used.
    - path: "scripts/**"
      instructions: >
        Scripts must be idempotent and exit non-zero on failure.
        Flag sed/awk parsing of source code regexes (use Python instead).
    - path: "docs/**"
      instructions: >
        Check factual accuracy. Flag stale dates or broken links.
        Verify any claimed feature exists in the codebase.
    - path: "apps/api/src/routes/**"
      instructions: >
        Verify response shape matches documented API contracts.
        Flag route handlers that parse but don't persist (ingest anti-pattern).
        Check auth enforcement — no route should be unprotected unless explicitly public.
    - path: "packages/shared-llm/**"
      instructions: >
        Flag JSON.parse() on raw LLM output (use multi-strategy extractor).
        Flag || with LLM response fields (use ?? nullish coalescing).
        Verify timeout hierarchy: agent < executor < HTTP.
    - path: "**/requirements*.txt"
      instructions: >
        All Python dependencies must use exact pinning (==, not >= or ~=).
        Flag any version that looks fabricated — check that major.minor.patch
        is a plausible release (e.g. 0.18.5 for a package whose 0.18.x ends at 0.18.3).
    - path: ".github/workflows/**"
      instructions: >
        Verify AUTH_MODE=strict in CI (never AUTH_MODE=open).
        Check that env vars are set for both Railway and Vercel.
chat:
  auto_reply: true
tone_instructions: >
  Direct, technical. Multi-LLM codebase. Flag hallucinated imports, fabricated APIs, stub returns, empty catches. Require evidence for claimed behavior. Recommend CI escalation for 3x repeat patterns.
