export type { IngestResult, IngestOptions, Ingester, ChunkStrategy, SourceType } from './types.js';
export { computeContentHash } from './types.js';
export { IngesterRegistry } from './registry.js';
export { chunkFixed, chunkSlidingWindow, chunkPerEntity, chunkSemantic, selectChunker } from './chunking/index.js';
export { DocumentIngester } from './adapters/document.js';
export { AudioIngester } from './adapters/audio.js';
export { ImageIngester } from './adapters/image.js';
export { WebIngester } from './adapters/web.js';
export { CsvIngester } from './adapters/csv.js';
export { ApiFeedIngester } from './adapters/api-feed.js';
export { computeFreshnessMultiplier } from './freshness.js';
export { isHashDuplicate, cosineSimilarity, NEAR_DEDUP_THRESHOLD } from './dedup/index.js';
export type { NearDedupResult } from './dedup/index.js';
export { createIngestionQueue, JobType } from './pipeline/queue.js';
export type { JobTypeValue } from './pipeline/queue.js';
export type { IngestionJobData } from './pipeline/jobs.js';
export { createIngestionWorker } from './pipeline/workers.js';
export { parseRedisConnection } from './pipeline/connection.js';
export type { RedisConnectionOptions } from './pipeline/connection.js';
